
import { type Cuisine } from '@/lib/types';

// Define our cuisine data with flag emojis
export const CUISINES: Cuisine[] = [
  {
    id: 'c1',
    name: 'Italiaans',
    pantryIngredients: [
      'Pasta (diverse soorten)',
      'Risottorijst',
      'Polenta',
      'Olijfolie',
      'Knoflook',
      'Tomaten',
      'Basilicum',
      'Oregano',
      'Rozemarijn',
      'Tijm',
      'Salie',
      'Parmezaanse kaas',
      'Balsamico azijn',
      'Rode peper vlokken',
      'Pijnboompitten'
    ],
    emoji: '🇮🇹'
  },
  {
    id: 'c2',
    name: 'Mexicaans',
    pantryIngredients: [
      'Maistortillas',
      'Bloem tortillas',
      'Rijst',
      'Bonen',
      'Maismeel',
      'Komijn',
      'Chilipoeder',
      'Oregano',
      'Kaneel',
      'Koriander',
      'Ancho chili',
      'Chipotle',
      'Limoen',
      'Uien',
      'Salsa',
      'Avocado'
    ],
    emoji: '🇲🇽'
  },
  {
    id: 'c3',
    name: 'Chinees',
    pantryIngredients: [
      'Rijst',
      'Noedels',
      'Wonton wrappers',
      'Sojasaus',
      'Oestersaus',
      'Gember',
      'Knoflook',
      'Rijstazijn',
      'Sesamolie',
      'Bosui',
      'Sriracha',
      'Hoisinsaus',
      'Vijfkruidenpoeder',
      'Szechuan peper',
      'Witte peper'
    ],
    emoji: '🇨🇳'
  },
  {
    id: 'c4',
    name: 'Mediterraans',
    pantryIngredients: [
      'Couscous',
      'Bulgur',
      'Pita brood',
      'Rijst',
      'Olijfolie',
      'Knoflook',
      'Citroenen',
      'Kikkererwten',
      'Tahini',
      'Za\'atar',
      'Sumak',
      'Komijn',
      'Yoghurt',
      'Feta kaas',
      'Oregano',
      'Komkommer',
      'Olijven'
    ],
    emoji: '🇬🇷'
  },
  {
    id: 'c5',
    name: 'Indiaas',
    pantryIngredients: [
      'Basmati rijst',
      'Chapati meel',
      'Naan',
      'Aardappelen',
      'Kerriepoeder',
      'Garam masala',
      'Kurkuma',
      'Komijn',
      'Korianderzaad',
      'Kardemom',
      'Kaneel',
      'Kruidnagel',
      'Venkelzaad',
      'Mosterzaad',
      'Asafoetida',
      'Koriander',
      'Gember',
      'Knoflook',
      'Yoghurt',
      'Ghee'
    ],
    emoji: '🇮🇳'
  },
  {
    id: 'c6',
    name: 'Amerikaans',
    pantryIngredients: [
      'Broodjes',
      'Aardappelen',
      'Maïs',
      'Bloem',
      'Ketchup',
      'Mosterd',
      'Mayonaise',
      'BBQ saus',
      'Knoflookpoeder',
      'Uienpoeder',
      'Cayenne peper',
      'Paprikapoeder',
      'Gerookt paprikapoeder',
      'Tijm',
      'Rozemarijn',
      'Boter',
      'Plantaardige olie',
      'Hot sauce'
    ],
    emoji: '🇺🇸'
  },
  {
    id: 'c7',
    name: 'Frans',
    pantryIngredients: [
      'Baguette',
      'Aardappelen',
      'Bloem',
      'Boter',
      'Witte wijn',
      'Rode wijn',
      'Sjalotjes',
      'Peterselie',
      'Tijm',
      'Laurierblad',
      'Rozemarijn',
      'Verse kruiden',
      'Dijon mosterd',
      'Room',
      'Cognac',
      'Truffels',
      'Herbes de Provence'
    ],
    emoji: '🇫🇷'
  },
  {
    id: 'c8',
    name: 'Japans',
    pantryIngredients: [
      'Sushirijst',
      'Udon noedels',
      'Soba noedels',
      'Ramen noedels',
      'Panko',
      'Sojasaus',
      'Mirin',
      'Sake',
      'Rijstazijn',
      'Dashi',
      'Miso',
      'Wasabi',
      'Shichimi togarashi',
      'Furikake',
      'Nori',
      'Gember',
      'Daikon'
    ],
    emoji: '🇯🇵'
  },
  {
    id: 'c9',
    name: 'Thai',
    pantryIngredients: [
      'Jasmijnrijst',
      'Rijstnoedels',
      'Kleefrijst',
      'Vissaus',
      'Kokosmelk',
      'Citroengras',
      'Thaise basilicum',
      'Heilige basilicum',
      'Galangal',
      'Gember',
      'Kaffir limoenblad',
      'Limoen',
      'Rode curry pasta',
      'Groene curry pasta',
      'Gele curry pasta',
      'Tamarinde',
      'Koriander',
      'Palmsuiker'
    ],
    emoji: '🇹🇭'
  },
  {
    id: 'c10',
    name: 'Grieks',
    pantryIngredients: [
      'Orzo',
      'Pita brood',
      'Bulgur',
      'Rijst',
      'Olijfolie',
      'Feta kaas',
      'Yoghurt',
      'Oregano',
      'Dille',
      'Munt',
      'Citroenen',
      'Knoflook',
      'Olijven',
      'Tomaten',
      'Komkommer',
      'Honing',
      'Kaneel'
    ],
    emoji: '🇬🇷'
  },
  {
    id: 'c11',
    name: 'Koreaans',
    pantryIngredients: [
      'Witte rijst',
      'Zoete rijst',
      'Noedels',
      'Gochujang',
      'Gochugaru',
      'Doenjang',
      'Sesamolie',
      'Sojasaus',
      'Koreaanse rijstazijn',
      'Knoflook',
      'Gember',
      'Kimchi',
      'Perilla blad',
      'Sesamzaad',
      'Aziatische peer',
      'Koreaanse radijs'
    ],
    emoji: '🇰🇷'
  },
  {
    id: 'c12',
    name: 'Spaans',
    pantryIngredients: [
      'Bomba rijst',
      'Aardappelen',
      'Brood',
      'Olijfolie',
      'Knoflook',
      'Paprikapoeder',
      'Pimentón (zoet en pikant)',
      'Saffraan',
      'Rozemarijn',
      'Tijm',
      'Laurierblad',
      'Kaneel',
      'Chorizo',
      'Tomaten',
      'Sherry azijn',
      'Sherry',
      'Amandelen'
    ],
    emoji: '🇪🇸'
  },
  {
    id: 'c13',
    name: 'Indonesisch',
    pantryIngredients: [
      'Witte rijst',
      'Noedels',
      'Ketjap manis',
      'Ketjap asin',
      'Sambal',
      'Sambal badjak',
      'Sambal oelek',
      'Kokosmelk',
      'Citroengras',
      'Galangal',
      'Kaffir limoenblad',
      'Trassi',
      'Tamarinde',
      'Laos',
      'Kurkuma',
      'Komijn',
      'Korianderzaad',
      'Kaneelstokjes',
      'Kruidnagel'
    ],
    emoji: '🇮🇩'
  }
];
