
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bddqqitjdfbtsqkitfim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZHFxaXRqZGZidHNxa2l0ZmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2OTUzNjIsImV4cCI6MjA1NzI3MTM2Mn0.pNPWROQGjPKlJ2ORzWRP47cncrzkJtSXuwbMAVyQgiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
      'X-Client-Info': 'recipe-generator-app'
    },
  },
  // Adding additional security options
  db: {
    schema: 'public'
  }
});

// Helper function to safely handle authentication
export const handleAuthErrors = (error: any): string => {
  // Log error to console, but return a sanitized message to the user
  console.error('Authentication error:', error);
  if (error?.message) {
    if (error.message.includes('Email not confirmed')) {
      return 'Please verify your email address';
    }
    if (error.message.includes('Invalid login credentials')) {
      return 'Invalid email or password';
    }
    if (error.message.includes('User already registered')) {
      return 'An account with this email already exists';
    }
  }
  return 'An error occurred during authentication';
};
